name: 'Divido Testing Deploy'
description: 'Deploy to testing environements via override'
inputs:
  service-name:
    description: 'Name of the service'
    required: true
  service-version:
    description: 'Version of the service'
    required: true
  environment:
    description: 'The testing environment to put the override in'
    required: true
  org_name:
    description: 'The org'
    required: false
    default: 'adam-putland'
  
  # Input not required from the user
  github_token:
    description: The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs }}.
      shell: bash

    - uses: actions/checkout@v2
      with:
          repository: ${{ inputs.org_name }}/${{ inputs.environment }}
          token: ${{ inputs.github_token}}
          path: ${{ inputs.environment }}

    - uses: EndBug/add-and-commit@v4
      with:
        author_name: adam
        author_email: adam.putland@divido.com
        message: "fix(autocomit): Automatic service bump"
        add: "."
        cwd: "./{{ inputs.environment }}"
        force: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token}}
